build:
    environment:
        php:
            version: 7.1
    tests:
        override:
            -
                command: 'vendor/bin/phpunit'
checks:
    php:
        excluded_dependencies:
            - leafo/scssphp
            - intervention/image
            - symfony/routing
