## development config file.

imports:
    - ../config.yml

environment: development

## Configure the paths of several directories
directories:
    ## The source directory
    src: ../src

    ## The public directory for the dev controller is used to save images
    public: ./

    ## Cache directory used by smarty
    cache: ./cache

    ## Template directory
    template: ../src/template

## Configure engines
engines:

    ## Don't optimize images. Disabling this option will increase the DevController's rendering speed,
    ## but will render less optimised images.
    optimizer: false

    ## Don't minify CSS or JS files in development
    minifier: false

