# The production config uses a few different paths to load files.
# There are also only some image dimensions specified by default.

# This production environment should be accessed via a separate virtual host.
# An Apache example of such host configuration could be:
#
# <VirtualHost *:80>
#     DocumentRoot "<path_to_project>/public"
#     ServerName stitcher.local
#     ErrorLog "<log_path>/error.log"
#     CustomLog "<log_path>/access.log" common
#
#     <Directory "<path_to_project>/public">
#         AllowOverride All
#         Require all granted
#     </Directory>
# </VirtualHost>

# Set the environment. Can be `production` or `development`
environment: production

# Render pages asynchronously, usually resulting in better performance.
# This only works when `ext-pcntl` is enabled. Run `php -i | grep pcntl` for more info.
async: false

# Configure the paths of several directories
directories:
    # The source directory
    src: ./src

    # The public directory in which the site is generated
    public: ./public

    # The cache directory
    cache: ./cache

    # Template directory
    template: ./src/template

# Configure meta tags
meta:
    viewport: width=device-width, initial-scale=1

# Add automatic www. redirect for all pages
redirect.www: true

# Add automatic https:// redirect for all pages
redirect.https: true

# When set to the host, a `sitemap.xml` file will be generated here
# sitemap.url: https://www.stitcher.io

# Configure engines
engines:
    # Choose the template engine. Available options: smarty, twig
    template: smarty

    # Use gd as image engine. Possible configurations: `gd` or `imagick`.
    image: gd

    # Try to use several system image optimizers
    optimizer: true

    # Enable CSS and JS minifier
    minifier: true

# A list of libraries and resources which should be delivered as-is, without parsing.
cdn:
#    - lib/js/file.js
#    - lib/css/

cache:
    # Enable image caching while rendering
    images: true

    # Cache CDN resources
    cdn: true
