## Please refer to https://www.stitcher.io/guide/setting-up for a complete guide on setting up a Stitcher project.

##################
# CONFIG OPTIONS
##################

## Import other config files. Properties can be overridden of the parent config.
# imports:
#    - ./my_main_config.yml

## Enable plugins by referencing their namespace here.
## More info can be found here: https://www.stitcher.io/guide/basic-plugin
# plugins:
#    - My\Plugin\Namespace\MyPlugin

################
# CORE OPTIONS
################

## Set the environment. Can be `production` or `development`
environment: production

## Render pages asynchronously, usually resulting in better performance.
## This only works when `ext-pcntl` is enabled. Run `php -i | grep pcntl` for more info.
async: false

## Configure the paths of several directories
directories:
    ## The source directory
    src: ./src

    ## The public directory in which the site is generated
    public: ./public

    ## The cache directory
    cache: ./cache

    ## Template directory
    template: ./src/template

## Configure engines
engines:
    ## Choose the template engine. Available options: smarty, twig
    template: smarty

    ## Use gd as image engine. Possible configurations: `gd` or `imagick`.
    image: gd

    ## Try to use several system image optimizers
    optimizer: true

    ## Enable CSS and JS minifier
    minifier: true

cache:
    ## Enable image caching while rendering
    images: true

    ## Cache CDN resources
    cdn: true

#####################
# RENDERING OPTIONS
#####################

## Configure default meta tags
meta:
    viewport: width=device-width, initial-scale=1

## Add automatic www. redirect for all pages
redirect.www: true

## Add automatic https:// redirect for all pages
redirect.https: true

## When set to the host, a `sitemap.xml` file will be generated here
# sitemap.url: https://www.stitcher.io

## A list of libraries and resources which should be delivered as-is, without parsing.
# cdn:
#    - lib/js/file.js
#    - lib/css/
