services:

    app.console:
        class: Brendt\Stitcher\Application\Console
        calls:
            - [add, ['@command.generate']]
            - [add, ['@command.clean']]
            - [add, ['@command.install']]
            - [add, ['@command.router.dispatch']]
            - [add, ['@command.router.list']]

    app.dev.controller:
        class: Brendt\Stitcher\Application\DevController
        arguments:
            - '@stitcher'

    stitcher:
        class: Brendt\Stitcher\Stitcher
        arguments:
            - '%directories.src%'
            - '%directories.public%'
            - '%directories.template%'
            - '%cdn%'
            - '%caches.cdn%'
            - '@parser.site'
            - '@service.htaccess'

    # Command
    command.generate:
        class: Brendt\Stitcher\Command\GenerateCommand
        arguments: ['%directories.public%', '@stitcher', '@service.event.dispatcher']
    command.clean:
        class: Brendt\Stitcher\Command\CleanCommand
    command.install:
        class: Brendt\Stitcher\Command\InstallCommand
    command.router.dispatch:
        class: Brendt\Stitcher\Command\RouterDispatchCommand
        arguments: ['@stitcher']
    command.router.list:
        class: Brendt\Stitcher\Command\RouterListCommand
        arguments: ['@stitcher']

    # Adapter
    adapter.collection:
        class: Brendt\Stitcher\Adapter\CollectionAdapter
        arguments: ['@factory.parser', '@compiler.meta']
    adapter.filter:
        class: Brendt\Stitcher\Adapter\FilterAdapter
        arguments: ['@factory.parser']
    adapter.order:
        class: Brendt\Stitcher\Adapter\OrderAdapter
        arguments: ['@factory.parser']
    adapter.pagination:
        class: Brendt\Stitcher\Adapter\PaginationAdapter
        arguments: ['@factory.parser']
    adapter.limit:
        class: Brendt\Stitcher\Adapter\LimitAdapter
        arguments: ['@factory.parser']

    # Parser
    parser.default:
        class: Brendt\Stitcher\Parser\DefaultParser
    parser.file:
        class: Brendt\Stitcher\Parser\FileParser
        arguments: ['%directories.src%']
    parser.folder:
        class: Brendt\Stitcher\Parser\FolderParser
        arguments: ['@factory.parser', '%directories.src%']
    parser.image:
        class: Brendt\Stitcher\Parser\ImageParser
        arguments: ['@stitcher', '@factory.image']
    parser.json:
        class: Brendt\Stitcher\Parser\JsonParser
        arguments: ['@factory.parser', '%directories.src%']
    parser.markdown:
        class: Brendt\Stitcher\Parser\MarkdownParser
        arguments: ['%directories.src%']
    parser.sass:
        class: Brendt\Stitcher\Parser\SassParser
        arguments: ['@service.sass', '%directories.src%']
    parser.yaml:
        class: Brendt\Stitcher\Parser\YamlParser
        arguments: ['@factory.parser', '%directories.src%']

    # Compilers
    compiler.header.runtime:
        class: Brendt\Stitcher\Site\Http\RuntimeHeaderCompiler
    compiler.header.htaccess:
        class: Brendt\Stitcher\Site\Http\HtaccessHeaderCompiler
        arguments: ['@service.htaccess']
    compiler.meta:
        class: Brendt\Stitcher\Site\Meta\MetaCompiler

    # Factory
    factory.parser:
        class: Brendt\Stitcher\Factory\ParserFactory
        arguments: ['@service_container']
    factory.adapter:
        class: Brendt\Stitcher\Factory\AdapterFactory
        arguments: ['@service_container']
    factory.template:
        class: Brendt\Stitcher\Factory\TemplateEngineFactory
        arguments: ['@service_container', '%engines.template%']
    factory.image:
        class: Brendt\Image\ResponsiveFactory
        arguments: ['@configurator.image']
    factory.header.compiler:
        class: Brendt\Stitcher\Factory\HeaderCompilerFactory
        arguments: ['%environment%']
        calls:
            - [addHeaderCompiler, ['development', '@compiler.header.runtime']]
            - [addHeaderCompiler, ['production', '@compiler.header.htaccess']]
            - [addHeaderCompiler, ['test', '@compiler.header.htaccess']]

    # Configurator
    configurator.image:
        class: Brendt\Image\Config\DefaultConfigurator
        arguments:
            config:
                driver: '%engines.image%'
                publicPath: '%directories.public%'
                sourcePath: '%directories.src%'
                enableCache: '%caches.image%'
                optimize: '%engines.optimizer%'
                async: '%engines.async%'
                optimizerOptions: '%optimizer.options%'

    # Service
    service.sass:
        class: Leafo\ScssPhp\Compiler
        calls:
            - [addImportPath, ['%directories.src%']]
    service.minifier.css:
        class: \CSSmin
    service.twig:
        class: Brendt\Stitcher\Template\Twig\TwigEngine
        arguments: ['%directories.template%', '@service.template.plugin']
    service.smarty:
        class: Brendt\Stitcher\Template\Smarty\SmartyEngine
        arguments: ['%directories.template%', '%directories.cache%']
    service.template.plugin:
        class: Brendt\Stitcher\Template\TemplatePlugin
        arguments:
            - '@factory.parser'
            - '@factory.image'
            - '@service.minifier.css'
            - '%directories.public%'
            - '%directories.src%'
            - '%minify%'
            - '%meta%'
    service.htaccess:
        class: Brendt\Stitcher\Site\Http\Htaccess
        arguments: ['%directories.htaccess%']
        calls:
            - ['setRedirectWww', ['%redirect.www%']]
            - ['setRedirectHttps', ['%redirect.https%']]
    service.event.dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    parser.site:
        class: Brendt\Stitcher\Parser\Site\SiteParser
        arguments:
            - '%directories.src%'
            - '@service.event.dispatcher'
            - '@parser.page'
            - '@service.htaccess'
            - '%meta%'

    parser.page:
        class: Brendt\Stitcher\Parser\Site\PageParser
        arguments:
            - '%directories.template%'
            - '@factory.adapter'
            - '@factory.parser'
            - '@factory.header.compiler'
            - '@factory.template'
            - '@service.template.plugin'
            - '@compiler.meta'
